name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Project
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t demo .

      - name: Run Container
        run: docker run -d -p 8089:8081 demo
